# Obfuscated by the Botpalys encoder
#Time: Tue May  5 07:25:45 2026
_ = lambda __ : __import__('base64').b64decode(__[::-1]);exec((_)(b'KkSKo4Wah1GKuVncu8Waj5WezFGIgACIKojIf9lbpFWbf9lIg0TPg81Xl1WYu91XgYWaKogCpgCZlR3Yl5mbvN2cpR2XslGduV3XuVncuQnbllGbjBCdpF2dhBCIgAiCpIysDHJxgkWo6G+boRHIpl5uhjGIhd6uhPGIJFEIpF6woRHIn5Wo6Guc0BSblhHIUCo4gAyc1RXY0N3LgACIigCdulmcwBCIgAiCpIibNub4oNGIn5WYRSMIpFquh/Ga0BSaZub4oByboNGIJFEIpFquhzGI01quhLGIUCo4gASZtV3clJ3LgACIigCdulmcwBCIgAiCpIiLu4Sehqb4oNGIn5WYRSMI09mYgQncvBHc1NFIWS6nwLCK05WayBHIgACIKkiIp03JB9iTnAicvBSZtFmbyV2c15SZttHQoASfl1WYu9FdzJXam5SZttHI6AXr6GOauByZuNIxRSMIjOMkEDShcKuImhCdulmcwBCIgAiCpgSZt9FdldmL05WZpx2YgQXahdXYg0DIl1GIgACIK4mc1RXZyBCIgACIgACIKkiIuckTJJFVT9lTPl0UTV0UgQXr6GOauBCctqb4jBSejOMSg4ibhqb4oBCd/qb4oByoDHJxgM2t6G+boByh7GObgA3o7GOagcmb0OMarBibvl2czV2UgwYniLCK05WayBHIgACIgACIgogOpgCZlpXay9Ga0VXYfJXZzV3XzlmL05WZpx2YgQXahdXYgQ3buBiZpBCIgAiCpgCdjVmbu92YuQnbllGbjBCdpF2dhBCIgAiC6kCKulWYtBiZlRGIj5WezFmCKowczFGcgACIgACIgAiC642bpRHclNGeFBCdwV2Y4VGIgACIKkiIukHoD7GIp15uhDrxn5GIvh2YgkUQgkWo6GObgQXr6GuYgM4uhHJxgUWb1NXZy9CI1O8Ruxlbc1Hdztnbc11c1RXY0NFI09mQbJiZoQXakVmL05WZ2VGI0lWY3FGIgACIgACIgACIgAiCicmbZub4RSMI0Fquh/GagcmbhFJxgkUQgYJpfCvIgU2csVGIkV2c1FGcfBibpBCZpVHImlGIikCc/qb4pRHIjF7uhLHdgM6uhLHdgc5uhjGIn5WYRSMIuFquhLGKgcmbrub4kBSbhqb4UBCuPKuIg0DI0NHIgACIgACIgACIgAiCklmLyVWZwBSPgQWa1BCIgACIgACIgACIgogOpIXZzVFIsIXZlBHKlNmbhR3cul2cpBiZpBCIgACIgACIKkCK0FGaj9FdldmL05WZ2VGI0lWY3FGI9AiclVGcgACIgACIgAiC6knc0BCIgAiC6kCduVmdlhyc1RXY0N3Xk12YfBiZlRGIj5WezFmCpkSZ0FmdpJHcfNXauUGI6UGIhRmYtFGb9Mmb1ZGIsICJzVHdhR3cv4VKp9DKiIXPuJXZ0RXYwBCLlVncU1zZul2bnRXdvhSZnF2czVWT3VmTuMHduVmdlhibv5CduVWasNGQKogCzNXYwBCIgACIgACIKojbvlGdwV2Y4VEI0BXZjhXZgACIgoQKoUGdlxWZk5CduVmdlBCdpF2dhBCIgACIgACIgACIgoQKklmLyVWZwhSZtV3clJ3XgACIgACIgACIgACIKoTKyV2cVBCLyVWZwhSZj5WY0NnbpNXagYWagACIgACIgAiCpgCdhh2YfRXZn5CduVmdlBCdpF2dhBSPgIXZlBHIgACIgACIgogO5JHdgACIgogOpQnblZXZoUWb1NXZy9FZtN2XgYWZkByYul3chpQKpUGdhZXayB3XzlmLlBiOlBSYkJWbhxWPj5WdmBCLiQSZtV3clJ3LelSa/giIy1jbyVGd0FGcgwSZ1JHV9cmbp92Z0V3boU2ZhN3cl10dl5kLzRnblZXZo42buQnbllGbjBkCKowczFGcgACIgACIgAiC642bpRHclNGeFBCdwV2Y4VGIgACIKkCZp5iclVGcoQGZh5CZlNXdhB3XgACIgACIgACIgACIKoDdvJmLyVWZwBCdv5GIk5WYgkiclNXVgwiclVGcoU2YuFGdz5WazlGImlGIgACIgACIgoQKoQXYoN2X0V2ZuQnblZXZgQXahdXYg0DIyVWZwBCIgACIgACIKoTeyRHIgACIKoTK05WZ2VGKn5WavdGd192Xu92XgYWZkByYul3chpQKpUGdhZXayB3XzlmLlBiOlBSYkJWbhxWPj5WdmBCLlVncU1zZul2bnRXdvhSZnF2czVWT3VmTuMHduVmdlhibv5CduVWasNGQKogCpIiL1F2cgkWo6GObg06uhjGdgcmbyOMbgkWdWBiLpd5uhzGIhJHI5NquhjHIjOckEDCLpd5uhzGIulGWgwYniLCKk52bwNXZy5CduVmdlBCdpF2dhBCIgACIgACIKkiI9NGeltHI60HZpV3e9QWa1BSXy9mcyVGIp5WatV2RbJiZoQnbpJHcgACIgACIgAiC6MGelBychBibvlGdwV2Y4VEI0BXZjhXZgACIgoQK0hXZ05SZz52bwNXZyhCZu9GczVmcuQnblZXZgQXahdXYgACIgACIgAiCpQHelRHIsU2ZhN3cl12Xk5WZz5Cdhh2YoQWYlJHa091b05ybpNmb5NXYgQXahdXYg0DIlNnbvB3clJHIgACIgACIgACIgAiC6kiIn5WawlHdiACLkl2X0FGaj5CduVmdlhibvlGdjFmL05WZpx2YggGdpdHIj5WezFGIgACIgACIgogO5JHdgACIgogCpQWa1hCdhh2YfRXZn9FI9ACdhh2YgACIgogCuJXd0VmcgACIgACIgAiC6QHelRHI09mbgYWagACIgoQKoAXayR3cukiIiAicvBCd4VGduU2ZhN3cl1mL05WZ2VGKg0DI0hXZ0BCIgAiCKkCZpVHKkRWYuQWZt92YsV2dfBCIgACIgACIKM3chBHIgACIgACIgACIgAiC642bpRHclNGeFBCdwV2Y4VGIgACIgACIgoQK44CMoAXZlx2cu8Waj5WezFGI0lWY3FGIgACIgACIgACIgAiCpIiZpdmLl12bjxWZ3JCIsQWafRXYoNmL05WZ2VGKlxWam9FZuV2cuQnbllGbjBCdpF2dhBCIgACIgACIgACIgogO5JHdgACIgACIgAiC6QWZt92YsV2dfBibpBCdv5GIklWdgYWagACIgogCuJXd0VmcgACIgACIgAiC6QWZzVXYw9FIulGIklWdgYWagACIgogCklmLyVGZuV2cg0DIklWdgACIgogCuJXd0VmcgACIgACIgAiC6Q3bi5iclRmblNHIy9GIpIXZzVFIsIXZk5WZzhSZj5WY0NnbpNXagQ3buBiZpBCIgAiCpgiclRmblN3X0V2ZuQnblZXZgQXahdXYg0DIyVGZuV2cgACIgogOpQnblZXZocmbp12bj5Waf52bfBiZlRGIj5WezFmCpkSZ0FmdpJHcfNXauUGI6UGIhRmYtFGb9Mmb1ZGIsUWdyRVPn5Wat92YulGKldWYzNXZNdXZO5yc05WZ2VGKu9mL05WZpx2YApgCKkCZp9lclNXdoQmchN2cpRmLkVWbvNGbld3XgACIgoQKl52bOBCLkl2XyV2c1hCcvBnLzRXYoN2XyV2c19FIgACIKkCZp9lclNXdoQmchN2cpRmLkV2c1FGcfBCIgAiC6kCdulGI6QWafJXZzVHKl1WdzVmcfBiZlRmCKoQXkl2XyV2c1t1c0FGaj9lclNXdfBibyVHdlJHIgACIKkSXb1Tey9GdzlGaoQXYoN2X0JXY0NnLsVGZv1GI9ASXkl2XyV2c1t1c0FGaj9lclNXdfBCIgACIgACIKkCIgACIgACIgoALUBVTPJFUf1URUNVWT1jbvlGdjVnc0Nnbp9VblR3c5NHIgACIgACIgACIgAiCsICazFGbm1SNuMTLp5WatV2Zi0TZtFmbfxWZk9WbgACIgACIgACIgACIKgCblR2bNVmdpRXYyVmbldkLpFmbldGI9ACblR2btBCIgACIgACIKozc0FGaj9lclNXdfBibpBCdv5GIkl2XyV2c1BiZpBCIgAiC6kCdulGI6QWafJXZzVHK0FGaj9Fdld2XgYWZkpgCKkCK0V2cg0DI0V2cgoDZlNXdhB3XKkCK0V2cg0DI0V2cgoDZl12bjxWZ39lC9tHI9ACdjlGZgozc0FGaj9lclNXdfpgCpg0UBh0XJBVQgwCRJ9VSQFEIskyROlkUUN1XO9USTNVRThibvl2czV2Un5WayR3UoQnbllGbD1WYydWZsVGVg0DI05WZpx2YKoQKZV0SflEUB9VSOlUTFdUP5V2aflGchhSZyV3ZpZmbvNmLpFmbldmCKkCKwlmc0NnLpgCZhVmcuY2Xg0DIUBVTPJFUf1URUNVWTBCIgAiC6Y2XgMXYgkiI40iZ0VnI9cmbpR2bj5WZgwiIyJCIskiI0hHduQHct9mcwJCIskyXfVGbpZ2XfhSZtFmbylGZugGdhBnLz9GKul2bq5Ca0FGcuM3bo4WZw9GIoRXa3pgCiAyYEJzVn9UdTJGSvF1Zidzb2BlUkR2U1MnNSJjeV1yRyFUeTFmeJFkIg0DIZV0SflEUB9VSOlUTFdkCi0zY1JUQnFkVRNmTzNDVNJXV25EMmRmUCZnYJtGRrFlUwhGTotkVXN2V0g3Zx9VVKVndwg1buZzZ4wGNXFHcRt0c3dEZzMGdNdHbrRjV49keaB3RzgTLpZFTWdTMYdGMhd3Ya9mSMNkQJ52VYhETtRmb05mS4I3N2g1ZCFkTB5mbrBVUwVEVUpEZfVmTrVVbZljMWxkTupkSihXRn1ycSdkWUR0cudHaLJTLQh2cG10RzpGMQd2Up1ke1k0VJJXZ2IjUMZVb5pmRwhUTPhGZwgGbfpkSXJlMXhlVV5mQ4BDRGFUO3p3NvRHRJJWeHBFWqNVVYp2QuNFTP9lN4NEcykXSillQlB3VahXVIFzMVdld0RmW5cjZjN3TlR0TyN0ZwQ2bOJUZshmVD1EZmB3S5MkNNVXba9WWvdkT0BzYvpHelNVYaVETBhGUNlTU3kzQa5URuZmS2YTdCdmSPNHdWJUMiASPgckTJJFVT9lTPl0UTV0UKciYlVjY2AzN2cDMkJDMiJGZ5EGO1EDN1EjNxETO3ATOkdCI9ACSTFESflEUBpAN1gTM0cDMyASPgQUSflEUBpgCyV2cVBCdy9GctlGIzVGc5RnLsRnLu9Ga0VGblRHIt9mcmpgbvl2czV2Un5WayR3UgQncvBXbpBycu9WazNXZz5ibvhGdlxWZ0BSbvJnZKMHduVmdlBCL05WZpx2QtFmcnVGblRFI0J3bw1Wag42boRXZsVGdg02byZmCpFmbldGIzFGIpFWZ2lGdhJXZuV2ZuUGbn92bnBCdy9GctlmCz9GI0J3bw1WaK8Waj5WezFGI0J3bw1Wa'))@client.on(events.NewMessage(outgoing=True, pattern=r"(?i)^/resume$", func=lambda e: e.is_private))
async def _cmd_resume(event):
    try:
        peer = await event.get_chat()
        if isinstance(peer, User):
            _resume(peer.id)
            await event.delete()
    except Exception:
        pass


@client.on(events.NewMessage(outgoing=True, pattern=r"(?i)^/status$", func=lambda e: e.is_private))
async def _cmd_status(event):
    try:
        peer = await event.get_chat()
        if isinstance(peer, User):
            uid = peer.id
            st = "⏸ Tạm dừng (bạn đang hỗ trợ trực tiếp)" if uid in _paused else "🤖 AI đang hoạt động"
            await event.edit(f"[Bot Status]\n{st}\n\nGõ /resume để bật lại AI cho người này.")
    except Exception:
        pass


async def main():
    await client.connect()
    if not await client.is_user_authorized():
        print("❌ Session không hợp lệ hoặc đã hết hạn. Hãy cập nhật SESSION_STRING.")
        return
    me = await client.get_me()
    print(f"✅ Đã đăng nhập: {me.first_name} (@{me.username or 'N/A'})")
    print("🤖 Support bot đang chạy...")
    print("   /resume  — bật lại AI cho hội thoại đang chọn")
    print("   /status  — xem trạng thái AI của hội thoại đó")
    await client.run_until_disconnected()


if __name__ == "__main__":
    asyncio.run(main())
